/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

/**
 *
 * @author sheva
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        KolomAlamat = new javax.swing.JTextField();
        Alamat = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        KolomNama = new javax.swing.JTextField();
        KolomKelas = new javax.swing.JTextField();
        Kelas1 = new javax.swing.JLabel();
        KolomAlamat1 = new javax.swing.JTextField();
        Alamat1 = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        KolomNama1 = new javax.swing.JTextField();
        KolomKelas1 = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setText("FORMULIR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 230, 80);

        Kelas.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Kelas.setText("Kelas");
        getContentPane().add(Kelas);
        Kelas.setBounds(50, 150, 70, 30);

        KolomAlamat.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        KolomAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(KolomAlamat);
        KolomAlamat.setBounds(130, 200, 270, 30);

        Alamat.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Alamat.setText("Alamat");
        getContentPane().add(Alamat);
        Alamat.setBounds(50, 200, 70, 30);

        Nama.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Nama.setText("Nama");
        getContentPane().add(Nama);
        Nama.setBounds(50, 100, 70, 30);

        KolomNama.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        KolomNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomNamaActionPerformed(evt);
            }
        });
        getContentPane().add(KolomNama);
        KolomNama.setBounds(130, 100, 270, 30);

        KolomKelas.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        KolomKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomKelasActionPerformed(evt);
            }
        });
        getContentPane().add(KolomKelas);
        KolomKelas.setBounds(130, 150, 270, 30);

        Kelas1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Kelas1.setText("Kelas");
        getContentPane().add(Kelas1);
        Kelas1.setBounds(50, 370, 70, 30);

        KolomAlamat1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        KolomAlamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomAlamat1ActionPerformed(evt);
            }
        });
        getContentPane().add(KolomAlamat1);
        KolomAlamat1.setBounds(130, 420, 270, 30);

        Alamat1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Alamat1.setText("Alamat");
        getContentPane().add(Alamat1);
        Alamat1.setBounds(50, 420, 70, 30);

        Nama1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Nama1.setText("Nama");
        getContentPane().add(Nama1);
        Nama1.setBounds(50, 320, 70, 30);

        KolomNama1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        KolomNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomNama1ActionPerformed(evt);
            }
        });
        getContentPane().add(KolomNama1);
        KolomNama1.setBounds(130, 320, 270, 30);

        KolomKelas1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        KolomKelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KolomKelas1ActionPerformed(evt);
            }
        });
        getContentPane().add(KolomKelas1);
        KolomKelas1.setBounds(130, 370, 270, 30);

        OKButton.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OKButton);
        OKButton.setBounds(210, 260, 90, 30);

        setBounds(0, 0, 516, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void KolomAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomAlamatActionPerformed

    private void KolomNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomNamaActionPerformed

    private void KolomKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomKelasActionPerformed

    private void KolomAlamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomAlamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomAlamat1ActionPerformed

    private void KolomNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomNama1ActionPerformed

    private void KolomKelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KolomKelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KolomKelas1ActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        String nama = KolomNama.getText();
        KolomNama1.setText(nama);
        String kelas = KolomKelas.getText();
        KolomKelas1.setText(kelas);
        String alamat = KolomAlamat.getText();
        KolomAlamat1.setText(alamat);
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Alamat1;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Kelas1;
    private javax.swing.JTextField KolomAlamat;
    private javax.swing.JTextField KolomAlamat1;
    private javax.swing.JTextField KolomKelas;
    private javax.swing.JTextField KolomKelas1;
    private javax.swing.JTextField KolomNama;
    private javax.swing.JTextField KolomNama1;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
